### ISSUE TITLE
Top extra cloud layer rendering at same height as vanilla clouds

### ISSUE THREAD

**Issue by Slooshie1** [Soulphur0/ElytraAeronautics#4]
![Minecraft Screenshot 2022 01 11 - 18 25 33 00](https://user-images.githubusercontent.com/90230538/149053007-fc746317-5831-4eb3-bbf5-3504fd8e0114.png)
I have 3 extra cloud layers, each 64 blocks apart, and I am using Iris to change the cloud height to 255. The top layer is currently z-fighting with the vanilla clouds. Also, on other configurations, I believe when I had 7 extra layers 16 blocks apart, the top layer was actually significantly lower than the vanilla clouds. So it seems that some tweaking with how the mod detects vanilla clouds and/or where to position extra clouds needs to happen. Other than that, this mod is great! I love the cloud layers, and I love the elytra physics.

**Comment by Soulphur0** [comment]
Thank you for reporting this. Right now the "default" cloud height that the mod uses to position and render the lowest clouds is 192, the vanilla cloud height, that is temporal. 

I will make it so is uses the cloud height the game is using at the time. 

I even have considered to remove vanilla clouds and make them a cloud layer by default so they behave like the rest and don't mess around with other cloud layers, but I will have to give it some thought.

**Comment by Soulphur0** [comment]
Elytra Aeronautics' cloud layers now override vanilla cloud rendering, this option can be disabled, or a cloud layer at Y=192 can be added along with others to have a cloud layer at vanilla cloud height.

The positioning of cloud layers, when specified, should 100% reflect the specified settings.

Feel free to open another issue if there's any other problem!
